### ISSUE TITLE
TEtranscripts error after install

### ISSUE THREAD

**Issue by Anna-xu408** [mhammell-laboratory/TEtranscripts#128]
Hi:

Thank you for wonderful tool.

After `$ python set.py install`

then `$ TEtranscripts -h`
it has an error：
```
Traceback (most recent call last):
  File "/home/bio/miniconda3/envs/TEtranscripts2.7/bin/TEtranscripts", line 4, in <module>
    __import__('pkg_resources').run_script('TEtranscripts==2.2.3', 'TEtranscripts')
  File "/home/bio/miniconda3/envs/TEtranscripts2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bio/miniconda3/envs/TEtranscripts2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/TEtranscripts' not found in metadata at '/home/bio/soft/TEtranscripts/TEtranscripts.egg-info'
```

So, how to solve it? I need your help

Thank you,
Anna

**Comment by olivertam** [comment]
Hi Anna,

One quick thing to check:
Are you typing `TEtranscripts -h` in the same folder where you installed the software (i.e. in the folder with the python install script)? If so, please move to another folder and try typing `TEtranscripts -h`.
It might be confused as to which `TEtranscripts` you're trying to access.
If that doesn't work, I'll be happy to troubleshoot further.

Thanks.
