### ISSUE TITLE
No module named setuptools

### ISSUE THREAD

**Issue by GimenaA** [mhammell-laboratory/TEtranscripts#211]
Hello,
I've used TEtranscripts in the past, but now I'm trying to install it in a new computer.  However, when I enter "python setup.py install" I get this error message:
`Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named setuptools`

I tried installing setuptools with pip3 but it's not solving the problem. Can you please help me?

**Comment by olivertam** [comment]
Hi,

Could you provide information on your `python`?
```
$ python --version
$ echo $PYTHONPATH
```

Thanks.

**Comment by GimenaA** [comment]
Thank you for your quick reply.

**python --version**
Python 2.7.18
**python3 --version**
Python 3.8.5
**echo $PYTHONPATH**
appears blank

**Comment by GimenaA** [comment]
I also tried installing it with **pip3 install TEtranscripts** like you suggested. It installed successfully, but when I try to use TEtranscripts I get a new error:
```
Traceback (most recent call last):
  File "/home/gimena/.local/bin/TEtranscripts", line 30, in <module>
    import pysam
  File "/home/gimena/.local/lib/python3.8/site-packages/pysam/__init__.py", line 16, in <module>
    import pysam.libcsamfile as libcsamfile
  File "pysam/libcsamfile.pyx", line 1, in init pysam.libcsamfile
  File "pysam/libcalignedsegment.pyx", line 61, in init pysam.libcalignedsegment
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

I tried installing pysam, but I get this message: 
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pysam in ./.local/lib/python3.8/site-packages (0.22.0)
```

Thank you for your help

**Comment by olivertam** [comment]
Thanks for your quick reply.

It looks like you have two different versions of python on your system, and it's causing a conflict because `python` (which is the default way to call the interpreter to run TEtranscripts) is using version 2.7.18, whereas you're installing everything using `pip3`, which would correspond to `python3`. Thus when you installed `setuptools` with `pip3`, it went to `python3` and not `python`.

With your `pip3` installation of TEtranscripts, it appears that the issue is related to a python module called `bcrypt`, which is a dependency of `pysam`. This error has been reported [here](https://github.com/pyca/bcrypt/issues/274), but it sounds like it's something to do with your system environment. Without knowing how your system is set up, I'm not sure I could easily resolve this.

There are two options to bypass this:
1) Run `TEtranscripts` as a Docker/Singularity container (see our [README](https://github.com/mhammell-laboratory/TEtranscripts/blob/master/README.rst) for details)
2) Set up a self-contained environment (e.g. using conda or its derivative) with its own separate python, `TEtranscripts` and all its dependencies.

Let me know if anything is unclear.

Thanks.

**Comment by GimenaA** [comment]
Thank you so much for your help! I'll take a look at it tomorrow and see if I can solve the issues. Thanks again.


Best Regards,



Gimena Alegre

Research Associate

Department of Neurobiology

University of Massachusetts Medical School

Lazare Medical Research Building, Room 760B

364 Plantation Street, Worcester, MA 01605

Phone: (508)856-4415
________________________________

**Comment by GimenaA** [comment]
I was able to solve it by setting up a conda environment and then installing TEtranscripts like you suggested on the second option. Thank you.
